timestamp = 1693948329

[signatures]
# Client State
dwClientState = 59F19C
dwClientState_GetLocalPlayer = 180
dwClientState_IsHLTV = 4D48
dwClientState_Map = 28C
dwClientState_MapDirectory = 188
dwClientState_MaxPlayer = 388
dwClientState_PlayerInfo = 52C0
dwClientState_State = 108
dwClientState_ViewAngles = 4D90
clientstate_delta_ticks = 174
clientstate_last_outgoing_command = 4D2C
clientstate_choked_commands = 4D30
clientstate_net_channel = 9C

# Entity and Player
dwEntityList = 4E051DC
dwLocalPlayer = DEF97C
dwPlayerResource = 3231380
dwRadarBase = 523BCB4
m_bIsLocalPlayer = 3628
m_flSpawnTime = 103C0

# Input and Movement
dwForceAttack = 3233024
dwForceAttack2 = 3233030
dwForceBackward = 3233078
dwForceForward = 323306C
dwForceJump = 52C0F50
dwForceLeft = 3233084
dwForceRight = 3233090
dwInput = 52627B0

# Game and Rendering
dwGameDir = 63AE00
dwGameRulesProxy = 5334764
dwGetAllClasses = E10F84
dwGlobalVars = 59EE60
dwGlowObjectManager = 535FCB8
dwViewMatrix = 4DF6024
dwppDirect3DDevice9 = A62C0
model_ambient_min = 5A1194

# Mouse and Sensitivity
dwMouseEnable = 523E410
dwMouseEnablePtr = 523E3E0
dwSensitivity = DF3B98
dwSensitivityPtr = DF3B98
dwYawPtr = DF3928
dwZoomSensitivityRatioPtr = DF9398
m_yawClassPtr = DF3928
m_pitchClassPtr = 523E308

# Weapons and Equipment
dwWeaponTable = 526388C
dwWeaponTableIndex = 326C
is_c4_owner = 3EA8A0

# Miscellaneous
dwInterfaceLinkList = 99F7D4
dwSetClanTag = 8DAB0
dwbSendPackets = DD2D2
convar_name_hash_table = 301A0
interface_engine_cvar = 3FA9C
m_bDormant = ED
m_pStudioHdr = 2950
anim_overlays = 2990
set_abs_angles = 1EA950
set_abs_origin = 1EA790
force_update_spectator_glow = 3DD09A
find_hud_element = 53B03A40

[netvars]
# Player Properties
m_ArmorValue = 117CC
m_iHealth = 100
m_iTeamNum = F4
m_lifeState = 25F
m_fFlags = 104
m_bSpotted = 93D
m_bSpottedByMask = 980
m_iCrosshairId = 117DC
m_iCompetitiveRanking = 1A84
m_iCompetitiveWins = 1B88
m_bGunGameImmunity = 9990
m_bHasDefuser = 117DC
m_bHasHelmet = 117C0
m_bIsDefusing = 997C
m_bIsScoped = 9974
m_flLowerBodyYawTarget = 9ADC

# Movement and Position
m_vecOrigin = 138
m_vecVelocity = 114
m_vecViewOffset = 108
m_aimPunchAngle = 303C
m_aimPunchAngleVel = 3048
m_viewPunchAngle = 3030
m_thirdPersonViewAngles = 31E4
m_angEyeAnglesX = 117D0
m_angEyeAnglesY = 117D4
m_MoveType = 25B
m_Local = 2FCC

# Weapon Properties
m_hActiveWeapon = 2F08
m_hMyWeapons = 2F08
m_iClip1 = 3274
m_flNextPrimaryAttack = 3248
m_bInReload = 3248
m_fAccuracyPenalty = 3340
m_iState = 3268
m_flNextAttack = 2D80
m_iItemDefinitionIndex = 2FBA
m_iEntityQuality = 2FBC
m_iItemIDHigh = 2FD0
m_iAccountID = 2FD8
m_nFallbackPaintKit = 31D8
m_nFallbackSeed = 31DC
m_nFallbackStatTrak = 31E4
m_flFallbackWear = 31E0
m_szCustomName = 304C
m_OriginalOwnerXuidLow = 31D0
m_OriginalOwnerXuidHigh = 31D4
m_zoomLevel = 33E0
m_bStartedArming = 3400

# Bomb Properties
m_bBombTicking = 2990
m_bBombDefused = 29C0
m_flC4Blow = 29A0
m_hBombDefuser = 29C4
m_flTimerLength = 29A4
m_flDefuseLength = 29B8
m_flDefuseCountDown = 29BC
m_nBombSite = 2994

# Visuals and Rendering
m_clrRender = 70
m_flFlashDuration = 10470
m_flFlashMaxAlpha = 1046C
m_iGlowIndex = 10470
m_bUseCustomBloomScale = 9DA
m_bUseCustomAutoExposureMin = 9D8
m_bUseCustomAutoExposureMax = 9D9
m_flCustomBloomScale = 9E4
m_flCustomAutoExposureMin = 9DC
m_flCustomAutoExposureMax = 9E0
m_iFOV = 31F4
m_iFOVStart = 31F8
m_iDefaultFOV = 333C

# Game Rules
cs_gamerules_data = 0
m_SurvivalRules = D00
m_SurvivalGameRuleDecisionTypes = 1328
m_bIsValveDS = 7C
m_bFreezePeriod = 20
m_bBombPlanted = 9A5
m_bIsQueuedMatchmaking = 74

# Entity and Model
m_Collision = 320
m_CollisionGroup = 474
m_rgflCoordinateFrame = 474
m_hOwner = 29DC
m_hOwnerEntity = 14C
m_nModelIndex = 258
m_nViewModelIndex = 29D0
m_hViewModel = 3308
m_dwBoneMatrix = 268C
m_nForceBone = 268C
m_iMostRecentModelBoneCounter = 268C
m_flLastBoneSetupTime = 28C0
m_flSimulationTime = 268
m_nTickBase = 3440

# Observer
m_hObserverTarget = 339C
m_iObserverMode = 3388

# Miscellaneous
m_iShotsFired = 103E0
m_szLastPlaceName = 35C4
